### ISSUE TITLE
Phpword install issue

### ISSUE THREAD

**Issue by jfrocha** [monarc-project/MonarcAppFO-vagrant#2]
No problem with others repositories, just this one. Therefore, the deliverables don't work.

==> default: Failed to clone the git@github.com:monarc-project/monarc_phpword.git repository, try running in interactive
 mode so that you can enter your GitHub credentials
==> default:

==> default:   [RuntimeException]

==> default:   Failed to execute git clone --mirror 'git@github.com:monarc-project/monarc_phpword.git' '/root/.composer/
cache/vcs/git-github.com-monarc-project-monarc-phpword.git/'

**Comment by cedricbonhomme** [comment]
I also had this problem. I solved it on my side with the GitHub token.

**Comment by cedricbonhomme** [comment]
Finally solved here:
https://github.com/monarc-project/MonarcAppFO/commit/cb8e99587b2cbb6171e7e612c1a14632ac54a93d
